### ISSUE TITLE
__version__ import in setup.py file, imports requests library before it is installed

### ISSUE THREAD

**Issue by madarve** [databox/databox-python#4]
Hello there!

When trying to install databox from pypi by runnning `pip install databox`, the "requests" library is imported before the setup.py file is executed completely, this is due to the line:

https://github.com/databox/databox-python/blob/master/setup.py#L3

That tries to run the __init__ module (which in turn imports requests), before actually going through the `install_requires` line.

Any of the solutions here could work, https://packaging.python.org/guides/single-sourcing-package-version/

**Comment by VladaPetrovic** [comment]
Thanks, @madarve for reporting this and posting suggestions. I'll have a look later today and have it fixed.

**Comment by madarve** [comment]
Hey sorry to bring this up again, but while this is already fixed in Github, it's not yet in pypi, any word on an ETA for that? :) https://pypi.python.org/pypi/databox

**Comment by VladaPetrovic** [comment]
@madarve This is updated now also in `pypi`. Thanks again for reporting.
